config/routes.rb
Rails.application.routes.draw do

  root 'locations#index'

  get 'weather/current', :to => 'weather#current'
  post 'weather/current', :to => 'weather#current'

  resources :locations do 
     member do
      get :sync
    end
  end

end

app/models/location.rb
class Location < ActiveRecord::Base

  validates :lat, :lng, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  before_action :current_weather, only: [:show]

  def index
    @locations = Location.all
  end

  def show
    @location = Location.find(params["id"])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.address = check_for_address
    @location.forecast = GetWeather.by_coordinates(params["location"]["lat"], params["location"]["lng"])
    if @location.save
      redirect_to action: "index"
    else
      redirect_to action: "new"
    end
  end

  def edit
    @location = Location.find(params[:id])
  end

  def update
    @location = Location.find(params[:id])
    
    if @location.update_attributes(location_params)
      redirect_to action: "index"
    else
      render action: "edit"
    end 
  end

  def destroy
    if Location.find(params["id"]).destroy
      redirect_to action: "index"
    end
  end

  def sync
    @location = Location.find(params["id"])
    unless @location.last_sync_at == DateTime.now
      @location.update_attribute(:last_sync_at, DateTime.now)
      @location.update_attribute(:forecast, GetWeather.by_coordinates(@location.lat, @location.lng))
    end
    flash[:notice] = "Sync done!"
    redirect_to action: "index"
  end

  private

  def location_params
    params.require(:location).permit(:lat, :lng, :address)
  end  

  def check_for_address
    location = Location.where(lat: params["location"]["lat"], lng:params["location"]["lng"]).first
    if location.present?
       location.address
    else
      GoogleGeocoding.get_address(params["location"]["lat"], params["location"]["lng"])
    end
  end  

  def current_weather
    location = Location.find(params["id"])
    unless location.last_sync_at == Time.now
      location.update_attribute(:last_sync_at, Time.now)
      location.update_attribute(:forecast, GetWeather.by_coordinates(location.lat, location.lng))
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/locations/edit.html.erb
<h1>
  Edit location
</h1>
<% if @location_error.present? %>
<p><% @location_error %></p>
<% end %>
<p> <%= link_to "go to index", root_path %> </p>

<%= form_for @location do |f| %>

  <%= f.label :lat %>
  <%= f.text_field :lat %>
  </br>
  <%= f.label :lng %>
  <%= f.text_field :lng %>
  </br>
  <%= f.submit "update" %>

<% end %>

app/views/locations/index.html.erb
<%= link_to "Add new", new_location_path %>
</br>
<table style="width:100%">
  <tr>
    <td>Latitude</td>
    <td>Longitude</td> 
    <td>Address</td>
    <td>Last sync at</td>
    <td>Actions</td>
  </tr>
  <%- @locations.each do |location| %>
    <tr>
      <td><%= location.lat %></td>
      <td><%= location.lng %></td> 
      <td><%= location.address %></td>
      <td><%= location.last_sync_at %></td>
      <td>
        <%= link_to "Show", location_path(location) %>
        <%= link_to "Update", edit_location_path(location) %>
        <%= link_to "Delete", location_path(location),method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to "Sync",sync_location_path(location) %>
      </td>
    </tr>
  <% end %>
</table>

app/views/locations/new.html.erb
<h1>
  Get new location
</h1>
<% if @location_error.present? %>
<p><% @location_error %></p>
<% end %>
<p> <%= link_to "go to index", root_path %> </p>

<%= form_tag( '/locations/create' ) do  %>

  <%= label_tag :lat %>
  <%= text_field_tag :lat %>
  </br>
  <%= label_tag :lng %>
  <%= text_field_tag :lng %>
  </br>
  <%= submit_tag "create new" %>

<% end %>

app/views/locations/show.html.erb
<p> <%= link_to "Back to list", action: 'index' %> </p>
</br>
<table style="width:100%">
  <tr>
    <td>Latitude</td>
    <td>Longitude</td> 
    <td>Address</td>
    <td>Forecasts</td>
    <td>Last sync at</td>
  </tr>
    <tr>
      <td><%= @location.lat %></td>
      <td><%= @location.lng %></td> 
      <td><%= @location.address %></td>
      <td><%= @location.forecast %></td>
      <td><%= @location.last_sync_at %></td>
      </td>
    </tr>
</table>